### ISSUE TITLE
Nothing is generated

### ISSUE THREAD

**Issue by amrography** [johnylemon/laravel-apidocs#1]
Thank you for great effort you made.
 
I followed along with steps but when I am running `php artisan apidocs:generate` no docs was generated. No even any errors are shown.

Here's my files

> routes/api.php
```php
Route::post('v1/register', [AuthController::class, 'register'])->apidocs(RegisterEndpoint::class);
```

> app/Apidocs/Endpoints/RegisterEndpoint.php
```php
...
public function describe(): void
    {
        $this->title('Register')
            ->description('Register a new account');
    }
...
```

**Comment by amrography** [comment]
I tried to do some debugging in `vendor/johnylemon/laravel-apidocs/src/Console/Commands/GenerateApidocs.php`

```php
public function handle()
    {
        $data = Apidocs::export();
       dd($data)
        file_put_contents(config('apidocs.file_path'), json_encode($data));
    }
```

and I got this
```php
array:4 [
  "info" => array:3 [
    "version" => "1.0"
    "title" => "Laravel API documentation"
    "description" => "Laravel API documentation"
  ]
  "domain" => "http://laravel-api.test"
  "groups" => array:1 [
    "non-groupped" => array:2 [
      "name" => "Non-groupped"
      "description" => "Non-grouped endpoints"
    ]
  ]
  "endpoints" => []
]
```

**Comment by johnylemon** [comment]
@amrography Glad you found this package useful.

Which PHP and Laravel version you are using?
Is this route (`api//v1/register`) accessible via api?
Looks like this endpoint is not accessible via api.

**Comment by amrography** [comment]
My php:`7.3.25` & laravel:`^8.0`, What do you mean by accessible ?

This is a screenshot of a testing.
![Screen Shot 2020-12-03 at 13 18 26](https://user-images.githubusercontent.com/9614340/101007306-116b9200-356a-11eb-9eab-3ec31aa82de0.png)

**Comment by amrography** [comment]
It works!
I added `Route::post('v1/register', [AuthController::class, 'register'])->apidocs(RegisterEndpoint::class);` in `routes/web.php`, then run `php artisan apidocs:generate`. It generated the docs for 2 times(from web.php and api.php)

Then I removed route registration from `web.php` and run `php artisan apidocs:generate` and worked!

**Comment by johnylemon** [comment]
@amrography problem may be caused by route cache. Fixed this morning.
