### ISSUE TITLE
Use within Route::Resource or Route::ApiResource

### ISSUE THREAD

**Issue by twoavy-ms** [johnylemon/laravel-apidocs#2]
Thank you for this great package! Really nice way of handling api documentation!

As I mostly use Route::resource and Route::ApiResource instead of Route::get etc. it would be really nice to be able to add it apidoc as in: Route::resource('/rooms', "Rooms\RoomsController")->apidocs(\App\Apidocs\Endpoints\Rooms::class);

Is there a chance this can be easily added?

**Comment by johnylemon** [comment]
@twoavy-ms Glad you found this package useful.
I am looking for simple solution for that. This needs more effort, and I dont want to create tricky hacks for that.
Will update this thread within a few days.

**Comment by twoavy-ms** [comment]
Sounds great! Thank you very much for looking into that!

**Comment by johnylemon** [comment]
@twoavy-ms package updated. You can now use `->apidocs()` chain method after `resource` and `apiResource` call

**Comment by twoavy-ms** [comment]
Fantastic! Thank you very much!
